name: ci

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]

jobs:
    cypress:
        # only runs this job on successful deploy
        if: github.event.deployment_status.state == 'success'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run Cypress
              uses: cypress-io/github-action@v2
              env:
                  CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}

            # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions
            - name: Cypress tests passed
              if: ${{ success() }}
              # set the merge commit status check
              # using GitHub REST API
              # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
              run: |
                  curl --request POST \
                  --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                  --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                  --header 'content-type: application/json' \
                  --data '{
                  "context": "cypress",
                  "state": "success",
                  "description": "Cypress tests passed"
                  }'

            - name: Cypress tests fail
              if: ${{ failure() }}
              run: |
                  curl --request POST \
                  --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                  --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                  --header 'content-type: application/json' \
                  --data '{
                  "context": "cypress",
                  "state": "failure",
                  "description": "Cypress tests failed"
                  }'
